[theme]
name = "native"

[icons]
name = "awesome"

# [[block]]
# block = "disk_space"
# path = "/"
# alias = "/"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0

[[block]]
block = "net"


[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

# [[block]]
# block = "docker"
# interval = 2
# format = "{running}/{total}"

# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "music"
buttons = ["play", "next"]

[[block]]
block = "battery"
device = "/sys/class/power_supply/BAT1"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

# [[block]]
# block = "xrandr"
# icons = true
# resolution = true
# interval = 2
